# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Copia los archivos de dependencias
COPY package.json package-lock.json* ./

# Instala TODAS las dependencias, incluidas las de desarrollo
RUN npm install

# Copia el resto del proyecto
COPY . .

# Expón el puerto de desarrollo
EXPOSE 3000

# Inicia el servidor Next.js en modo dev (hot reload)
CMD ["npm", "run", "dev"]
